apiVersion: v1
binaryData:
  logo.jpg: {{ .Values.logo }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  index.html: <h1>Hello from Nginx :)</h1></br><img src="logo.jpg" alt="nginx">
  